project: 
  type: website
  
website: 
  page-navigation: true
  title: "The Fay Lab" 
  site-url: "https://thefaylab.com" 
  repo-url: https://github.com/thefaylab/thefaylab.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    right: This website is built with {{< fa heart title="a heart" >}}, {{< fa cat title="cats" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/thefaylab/thefaylab.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}, and [Quarto](https://quarto.org/){target=_blank}
    left: "&copy; CC-By FayLab 2025, Openscapes 2024"
    
  sidebar:
    logo: "images/thefaylab_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://thefaylab.com
        text: "thefaylab.com"
      - icon: github
        href: https://github.com/thefaylab
        text: "FayLab Github"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: jointhelab.qmd
        text: Opportunities
        
format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
