project:
  type: website
  resources:
    - images/team/**
    
website:
  title: "The Fay Lab"
  site-url: "https://thefaylab.com"
  repo-url: "https://github.com/thefaylab/thefaylab.github.io"
  repo-actions: [edit, issue]

  navbar:
    background: dark
    foreground: light
    pinned: true
    logo: images/thefaylab_hex.png
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: jointhelab.qmd
        text: Opportunities
    right:
      - icon: github
        href: https://github.com/thefaylab
      - icon: globe
        href: https://thefaylab.com
      - icon: search


format:
  html:
    theme: flatly
    css: styles.css
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
