---
title: "The Fay Lab, Quantitative Fisheries & Ecosystem-Based Management Science"
subtitle: "School for Marine Science and Technology, University of Massachusetts Dartmouth"

listing:
  - id: recent-blog-listing
    contents:
      - "blog/*/index.qmd"
    sort: "date desc"
    type: grid
    max-items: 3
    #page-size: 3
    categories: false
    sort-ui: false
    filter-ui: false
    fields: [title, image, date, categories]
---

:::::: white-div
**Welcome** to Gavin Fay’s lab at the University of Massachusetts Dartmouth.

[Read about our lab culture & philosophy.](https://thefaylab.github.io/lab-manual/02-lab-culture-philosophy.html)

Our research focuses on developing and testing quantitative modeling tools used for assessment and management of living marine resources, working to advance sustainable decision-making for our oceans and the people who depend on them in a changing world. We focus on decision support tools applied to management of fish, marine mammal, and reptile populations, regionally in the Northeast and Mid-Atlantic of the USA, as well as elsewhere nationally and internationally. A central theme is considering the performance of methods used for management given an ecosystem and socio-ecological systems perspective, and assessing the robustness of policy alternatives to a range of system uncertainties, including the impacts of climate change.

We embrace [open data science approaches](https://openscapes.org/) to help make our work more shareable, accessible, and reproducible. Common to all our work is an applied approach to improve the advice for science-based decision-making by living resource management agencies, and we collaborate and partner with these institutions and engage in their public decision-making processes.

[Lab Code of Conduct](https://thefaylab.github.io/lab-manual/03-code-of-conduct.html)

[Prospective graduate students](#futuregrads) may contact Gavin about his availability as a faculty advisor.

Current UMassD undergraduate students interested in working in the group should check [the opportunities section](#undergrads) for advertised marine data science research technician positions.

<!---------------- START blog listing section (white div) ---------------->

::::: white-div
:::: {.blue-underline .center-text}
### **Lab News**

<br> Our blog shares stories from the lab community and documents our learning openly. See the recent posts below or browse our [full blog listing](blog.qmd). <br>

::: {#recent-blog-listing}
:::
::::
:::::

<!---------------- END blog listing section (white div) ---------------->

<!---------------------------------------------------------------------->
::::::
