---
title: "Research"
---

## Research

Our research focuses on developing and testing quantitative modeling tools used for assessment and management of living marine resources, working to advance sustainable decision-making for our oceans and the people who depend on them in a changing world. We focus on decision support tools applied to management of fish, marine mammal, and reptile populations, regionally in the Northeast and Mid-Atlantic of the USA, as well as elsewhere nationally and internationally. A central theme is considering the performance of methods used for management given an ecosystem and socio-ecological systems perspective. We use ecosystem and population modeling to test the performance of fishery- and ecosystem-based management strategies and evaluate the robustness of management options to a range of system uncertainty, including climate change. To achieve these goals, we make use of and develop methods for stock and ecosystem assessment, and employ simulation frameworks including Management Strategy Evaluation. To support Integrated Ecosystem Assessment, we are increasingly working across disciplines to integrate dynamics of the human dimension into evaluation of management consequences of choices for human uses of the marine ecosystem.

We embrace principles and workflows from open data science to help make our work more shareable, accessible, and reproducible. Common to all our work is an applied approach to improve the advice for science-based decision-making by living resource management agencies; quantitative models and methods like MSE provide a transparent and explicit approach for quantifying tradeoffs among management objectives, often merely implicit in decision-making. Developing effective methods for visualizing and communicating these tradeoffs and management outcomes is an additional area of focus. We collaborate with scientists at state and federal agencies, international science organizations, and with regional fisheries management organizations. Graduate students in our lab all work closely with scientists at NOAA National Marine Fisheries Service, in Population Dynamics, Ecosystem Dynamics and Assessment, Surveys, and Protected Species.

Current and recent research topics include:

-   Using ecosystem models to test the performance of ecosystem-based fisheries management strategies in the Northeast US

-   Developing methods for managing New England groundfish fisheries under a changing climate

-   Assessing economic effects of fishing scenarios through ecological-economic model coupling

-   Evaluating performance of adaptations to scientific surveys due to spatial overlap with offshore wind installation areas

-   Ecosystem indicators as operational tools for fisheries management

-   Management of recreational fishery for summer flounder

-   Developing and testing spatial stock assessment models

-   Integrating telemetry information into assessment models for highly migratory species

-   Decision support tools for Integrated Ecosystem Assessment and Ecosystem-Based Management

-   Multispecies stock assessment models

### Research themes

#### Evaluating ecosystem-based fisheries management procedures

To operationalize ecosystem-based fisheries management, there needs to be well-tested on-ramps for including or accounting for ecosystem information in fisheries decisions, as well as understanding the performance of advice for management that includes (or doesn’t include) this information, including in the context of climate change. We have developed methods and frameworks to estimate and assess the importance of thresholds in indicators of ecosystem state given both human and environmental stressors. We tested the performance of management strategies that include fishery control rules which use the status of ecosystem indicators relative to ecosystem reference points to modify fishing mortality among species for a Georges Bank finfish community case study, and demonstrated that in some cases it is possible to improve against both economic and conservation objectives by including these indicators in decisions (see also Gaichas et al. 2017). Further work suggested that placing ceilings on system removals can also be a leading driver of multispecies fishery performance without the need for multispecies stock assessment models. Ongoing work is investigating how technical interactions and other constraints associated with the operation and management of multispecies fisheries affect the performance of these ecosystem approaches. With Dr. Lisa Kerr’s lab at Gulf of Maine Research Institute, we are also testing the performance of climate responsive management options for New England groundfish, and conducting a series of meetings with regional decision makers and stakeholders aimed at education around EBFM and benefits of management strategy evaluation for strategic decision-making in fisheries. Our work demonstrates how ecosystem indicator information could be used within current fisheries management frameworks. These results (along with others) form the basis for possible decision points in an example Fishery Ecosystem Plan under consideration for New England.

#### Ecosystem models to assess socio-ecological system outcomes

Ecosystem models, including whole-of-system or end-to-end models, enable tradeoffs to be quantified for a broader suite of societal and ecological objectives, allowing a more systemic look at possible outcomes for strategic management choices and uncertainties associated with forecasts. We have coupled regional economic models with the output of the ecosystem model Atlantis to calculate indicators associated with the effects of fishing strategies on jobs and earnings in the Northeast region as a whole as well as on seafood supply. We have also used these whole-of-system models to quantify plausible consequences of ocean acidification, and compare among marine ecosystems broad ecological and fishery outcomes of implementing Marine Protected Areas as part of management solutions in addition to different levels of fishing mortality and climate effects. While whole-of-system models can provide complex characterizations of coupled socio-ecological marine systems, they require data and resources, and may not be easy to fully evaluate implication of modeling choices. Qualitative and semi-quantitative models that characterize linkages within systems but do not rely on mechanistic models for dynamics of system components could be useful tools for integrating across human, physical, and ecological components of ecosystems, and for rapidly screening environmental and human use scenarios. Wildermuth et al. (2018) created a qualitative model for the Georges Bank socio-ecological system and evaluated how the ability to meet management objectives changed with alternatives for model structure. Our ongoing work as part of the ICES Working Group for the Northwest Atlantic Regional Sea (WGNARS) is evaluating what the role of these (and other) tools can be in the Integrated Ecosystem Assessment process (e.g. DePiper et al. 2017, WGNARS 2018; Wildermuth PhD thesis), developing best practices that are being incorporated in to the broader NOAA IEA program, being used by the Mid-Atlantic Fishery Management Council as part of their Ecosystem Approach to Fisheries, and also within the larger ICES community.

Challenges facing marine fisheries also include interactions with other marine uses, including the rapid increase of offshore wind energy. Development of offshore wind industry on the US east coast creates spatial overlap with installation areas and fisheries operations, and also requires adaptation to scientific monitoring to maintain data streams for fisheries and ecosystems used as the basis for fisheries management advice. As part of an interagency agreement between BOEM and NOAA Fisheries, we are using spatially explicit ecosystem modeling to test the effect of changes to scientific surveys as a result of spatial overlap with wind lease areas and evaluating the efficacy of supplemental monitoring strategies for data used in fisheries assessment models and management advice.

#### Integrated population modeling

Scientific advice for tactical fisheries management decisions, such as quota setting, and in-season management adjustments and projections rely on statistical tools for stock assessment and species distribution modeling that can account for ecosystem information and leverage data from multiple sources, including new and developing technologies. A range of data are often collected for highly migratory species of conservation concern (and increasingly for commercial fish too), however these data, such as electronic and acoustic tagging, and photo mark-recapture, are not often directly used with population assessment models. In addition, species distribution modelling approaches that use these data do not fully account for statistical properties of these data resulting in biased inferences. Point process models and integrated population models that take a hierarchical approach to spatial and individual heterogeneity offer feasible solutions for including these data directly in assessment models and species distribution models. We have developed and applied models of this type to estimate loggerhead sea turtle distribution based on satellite tagging, spatial distribution of fish from acoustic tags (Winton et al. 2018b), toothed whale distribution in Stellwagen Bank National Marine Sanctuary, and are applying integrated methods to white sharks in Massachusetts (Winton PhD thesis, in prep.) and to multispecies interactions between forage fish and their predators. Our work to develop statistical methods for population assessment has also included evaluating the performance of model selection tools for choosing between stock assessment models that differ in how the environment affects recruitment, important for considering how fisheries productivity may be expected to change in the future. Weston (MS thesis 2018) showed that currently used methods for choosing models are not reliable for distinguishing among these effects yet the consequences of incorrect model choices can be mitigated given adaptive management frameworks with responsive harvest control rules.

Fisheries are rarely prosecuted on a species-by-species basis. However, examples of integrated population models that account for process error and observation error of multiple data types and take a multispecies approach are limited. In Trijoulet et al. (2019) and Trijoulet et al. (2020) we developed a new multispecies state-space stock assessment model and tested its performance for assessing fisheries dynamics, evaluating the treatment of diet data along with more traditional stock assessment data sources in estimation bias. We are currently also expanding the capabilities of the length-based statistical multispecies fisheries model Hydra (Gaichas et al. 2017) for application to multispecies fisheries in the Norwegian and Barents Sea, and Georges Bank, including simulation testing using output from the Atlantis ecosystem model as a virtual laboratory. This work adds to the suite of modeling tools available for assessing the status of fisheries in New England and beyond, and a common approach across projects is to evaluate and compare the performance of new methods to current approaches using simulation testing.

### Sources of funding (2014-present, including from GF private consulting)

-   Atlantic States Marine Fisheries Commission
-   Boston Scientific Foundation
-   California Ocean Science Trust
-   Cooperative Institute for the North Atlantic Region (CINAR)
-   Department of Energy
-   Gulf of Maine Research Institute
-   International Council for the Exploration of the Sea (ICES)
-   Massachusetts Clean Energy Center
-   Massachusetts Division of Marine Fisheries
-   Mid-Atlantic Fishery Management Council
-   MIT Sea Grant
-   National Center for Ecological Analysis & Synthesis, UC Santa Barbara
-   National Science Foundation
-   New England Fishery Management Council
-   NOAA Climate Program Office
-   NOAA Fisheries & the Environment (FATE)
-   NOAA Fisheries Stock Assessment Analytical Methods
-   NOAA Fisheries Office of Science and Technology
-   NOAA Fisheries Quantitative Ecology and Socioeconomics Training Program (QUEST)
-   NOAA Northeast Fisheries Science Center
-   NOAA Office of National Marine Sanctuaries
-   NOAA Saltonstall Kennedy
-   NOAA Sea Grant
-   Science Center for Marine Fisheries, University of Southern Mississippi
-   Sound Resolutions LLC
-   The Nature Conservancy
-   University of Massachusetts Dartmouth Blue Economy
-   University of Massachusetts Dartmouth Marine & Undersea Science Technology Program (MUST)
-   Virginia Institute of Marine Sciences
-   Virginia Polytechnic Institute & State University
-   Woods Hole Oceanographic Institution
-   Woods Hole Sea Grant
