---
title: "Teaching"
format:
  html:
    toc: false
    css: /styles/teaching.css
---

#### Fall 2025 Offering

::: {.current-offer}
This semester (**fall 2025**) Dr. Fay will be offering **Advanced Population Modeling (MAR 580)**.

Students not at UMassD interested in taking MAR580, either remotely or in-person, should email Dr. Fay ASAP.
:::

<div class="course-list-grid">

<div class="course-card">
  <h4>MAR 580</h4>
  <h5>Advanced Population Modeling for Management of Living Marine Resources</h5>
  <p>This course provides instruction, demonstration, and exercises in advanced population modeling, as applied to fishery resources. Students will develop a wide range of stock assessment methods using statistical programming to fit increasingly complex models to fishery data. Programming software, including <strong>Template Model Builder</strong>, will be used for assignments. The course aims to train students to conduct high-quality scientific research in stock assessment and fishery population dynamics.</p>

<div class="course-info">
  <span>(*Fall semester, odd years*)</span>
  <a href="https://drive.google.com/file/d/1Of57_FEEY5-Gi-VjlFN2aDORwR6DC26x/view?usp=sharing" target="_blank">View 2023 Syllabus</a>
  <strong class="next-offered">Next Offered: Fall 2025</strong>
</div>
</div>

<div class="course-card">
  <h4>MAR 530</h4>
  <h5>Ecosystem-Based Fisheries Management (EBFM)</h5>
  <p>This course highlights the theory, challenges, and approaches for implementing ecosystem-based fisheries management (EBFM). The course examines the history and background of fisheries management, leading to why more holistic approaches are being considered. A series of operational methods being used to implement EBFM, emphasizing technical efforts and models, are reviewed. The role of institutional structures and societal considerations in decision-making are explored to identify situations where EBFM can be successful.</p>

<div class="course-info">
  <span>(*Spring semester, every other year*)</span>
  <a href="https://drive.google.com/file/d/16OVUzWxOGj1T-5zFYk4gA28o77SxsFCF/view?usp=sharing" target="_blank">View 2024 Syllabus</a>
  <strong class="next-offered">Next Offered: Spring 2026</strong>
</div>
</div>

<div class="course-card">
  <h4>MAR 522</h4>
  <h5>Science Communication for Research Scientists: delivering effective messages to diverse audiences</h5>
  <p>Practice and development of skills for communicating scientific research to a diverse set of audiences is important for applications to fisheries management and policy. This course is for students in the sciences and focuses on the importance of defining the ‘so what’ of research and adapting messaging to specific audiences, using storytelling techniques to produce compelling presentations of scientific research. Drawing on communication case studies and their own academic interests as context, students practice delivering their message effectively for different audiences, including defining goals, identifying main points, explaining meaning and context, responding to questions, and using multimedia elements. Students develop and apply skills for communicating their research to scientific peers, the management community, stakeholders, and the general public. In-class activities and assignments emphasize presentation skills, writing, reflection, and constructive criticism through peer-review of classmates’ work. The role of the review process for how best available science is incorporated into policy and decision-making in the context of fisheries management is used as a case study during the course. Topics and activities have relevance for many disciplines at the science-management-policy interface.</p>

<div class="course-info">
  <span>(*Fall semester, even years*)</span>
  <a href="http://www.smast.umassd.edu/lab_fay/wp-content/uploads/2020/05/MAR599_SciComm_syllabus_20200512.pdf" target="_blank">View 2024 Syllabus</a>
  <strong class="next-offered">Next Offered: Fall 2026</strong>
</div>
</div>

<div class="course-card">
  <h4>MAR 536</h4>
  <h5>Biological Statistics II</h5>
  <p>Student-led learning in statistical analysis of ecological data. This course provides guided learning in advanced statistical analysis, as applied to ecological research and other fields of marine science. Advanced concepts in probability, hypothesis testing, and estimation will be presented by students, including analyses of example data sets and problems. Students will be required to learn selected methods independently, present topics to the class that are relevant to their graduate research and complete a class project. A computer lab, focused on introductory and intermediate programming and analysis using R, will be held for the first half of the semester.</p>

<div class="course-info">
  <span>(*Spring semester, odd years*)</span>
  <a href="http://www.smast.umassd.edu/lab_fay/wp-content/uploads/2020/05/BiolStats2_syllabus_SPR2020_20200316.pdf" target="_blank">View 2025 Course Website</a>
  <strong class="next-offered">Next Offered: Spring 2025</strong>
</div>
</div>

<div class="course-card">
  <h4>MAR 580</h4>
  <h5>Models for Marine Ecosystem-Based Management</h5>
  <p>This course provides instruction, demonstration, and exercises in quantitative modeling tools used for Ecosystem Based Management (EBM) of living marine resources. There is an increasing need for fisheries and wildlife professionals to provide scientific advice for management in an ecosystem context. Part 1 of the course will provide students with hands on experience applying fisheries stock assessment and population models that include ecosystem effects, and consider the policy implications of including this information. Part 2 of the course will focus on broader multiple-use and human dimensions and include economic and behavioral models and models for marine spatial planning. The final section of the course will introduce whole-of-ecosystem models and demonstrate how these can be used to provide strategic advice for marine management and consider a broad suite of objectives. Although the examples used will be in a marine context, the types of models and methods discussed in the course have application in other systems.</p>

<div class="course-info">
  <span>(*occasional, last offered fall 2022,*)</span>
  <a href="https://gavinfay.github.io/mebm-models/" target="_blank">View 2022 Course Website</a>
  <strong class="next-offered">Next offered: TBD</strong>
</div>
</div>

<div class="course-card">
  <h4>MAR 595</h4>
  <h5>Bayesian Statistics and Hierarchical Modeling for Ecology</h5>
  <p>Independent study in Bayesian statistics and hierarchical modeling with an emphasis on mathematical statistics. Bayesian modeling has become an indispensable tool for ecological research. This course provides an overview of the principles of Bayesian statistics and concepts. Students will work through the recent textbook by Hobbs & Hooten (2015) with additional supplementary reading from the literature. A set of problems in the textbook are worked through using multiple methods, including writing out properly factored statistical expressions representing the Bayesian models, and implementation of models using current state-of-the art algorithms and software. Advanced topics in Bayesian methods will also be covered. Weekly meetings are used to review chapter readings, discuss additional key papers on weekly topics, and work through problems as a group. </p>

<div class="course-info">
  <span>(*Varies, last offered fall 2018*)</span>
  <a href="http://www.smast.umassd.edu/lab_fay/wp-content/uploads/2020/05/BayesianStats_syllabus_fall2018_20180906.pdf" target="_blank">View 2018 Syllabus</a>
  <strong class="next-offered">Next Offered: TBD</strong>
</div>
</div>

<div class="course-card">
  <h4>MAR 700</h4>
  <h5>Graduate Seminar, Fisheries Oceanography</h5>
  <p>Weekly departmental seminar series organized by Dr. Fay in various semesters. Includes presentations on topics in fisheries oceanography and related fields.</p>

<div class="course-info">
  <span>(*GF organized Spring 2015, Fall 2016, Spring 2018, Fall 2020, Fall 2023*)</span>
  <strong class="next-offered">Recent Schedules &amp; Videos:</strong>
  <ul>
    <li><a href="https://thefaylab.github.io/dfo-seminar-f23" target="_blank">Fall 2023 Schedule</a></li>
    <li><a href="http://www.smast.umassd.edu/lab_fay/wp-content/uploads/2018/05/DFO_Seminar_Poster_Spring2018.pdf" target="_blank">Spring 2018 Schedule (Poster)</a></li>
    <li><a href="http://www.smast.umassd.edu/lab_fay/wp-content/uploads/2015/04/DFO_Seminar_Poster_Spring2015_Apr23.pdf" target="_blank">Spring 2015 Schedule (Poster)</a></li>
    <li><a href="http://www.smast.umassd.edu/lab_fay/wp-content/uploads/2015/09/DFO_Seminar_Poster_Fall2015.pdf" target="_blank">Fall 2015 Schedule (Poster)</a></li>
    <li><a href="https://www.umassd.edu/media/umassdartmouth/smast/labpdffiles/archive_of_seminar_series.pdf" target="_blank">Links to Video Recordings Archive</a></li>
  </ul>
</div>
</div>

</div>
