---
title: "Conversations with recreational fishers about fisheries science"
author: Kamran Walsh
date: 2025-03-25
slug: recfishconv-kaw
categories:
  - blog 
 # - community
  - communication
 #  - students
---

# Conversations with recreational fishers about fisheries science

This past fall, PhD student Kamran Walsh (me) teamed up with He Lab Master’s student Kevin Bennett to interview recreational fishers throughout the southern New England area. This was part of Gavin’s Science Communication class, with the specific purpose of our exercise being to better understand how anglers in our community view science and management decisions. Our interviews were more conversational than formal, with topics touching upon past and ongoing research related to New England recreational fisheries, social justice issues in the community, and fisheries outside of New England. We ultimately wanted to provide an informal, safe setting for both scientists and stakeholders to learn from each other’s experiences and discuss their views. As someone who has fished nearly his whole life and seen plenty of conflict involving the shared use of marine resources, I was especially interested in learning about how other anglers feel about the work that SMAST and other nearby research institutions are engaging in. 

Over the course of several weeks that extended through the end of the 2024 recreational saltwater fishing season in New England, Kevin and I interviewed a diverse group of anglers and industry members in a variety of settings along Massachusetts’ South Coast, Cape Cod, and coastal Rhode Island. This included purely recreational anglers, charter captains, tackle store owners, tackle company employees, and even software developers of a new smartphone app geared towards improving recreational fisheries data collection. We learned that angler and industry members’ opinions towards research and management vary, particularly involving controversial regulations such as Striped Bass recreational measures. We also were pleasantly surprised to learn that the anglers we interviewed were often highly supportive of conservation efforts and research, with multiple interviewees expressing their support for current (even more restrictive) regulations and increased fisheries enforcement. Each of the people that we talked to had unique views towards fisheries that were heavily influenced by their cultural background, worldview, and way of life. It is also worth noting that anglers expressed nearly unanimously negative views towards offshore wind for a host of reasons, stressing the importance of accounting for this friction point in the future of ocean usage allocation and marine resources management. Ultimately, it was an enriching experience that provided an ideal environment not only to learn about anglers’ honest opinions of science and management, but the region’s fisheries and fishing cultures through the unique perspectives provided.  You can view the videos [here](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DypQZYaEhcK0&data=05%7C02%7Cgfay%40umassd.edu%7C97e2a7b9387046dc2c0a08dd566fb6a5%7C328d6c0d0f2f4b7693109762ba1c3e2d%7C0%7C0%7C638761760008081003%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=ISd2goVKPtvAcIw7g4R9aJb6Vvvrh%2FCJw3%2BHT1YZn2Q%3D&reserved=0) (part 1), [here](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DYTgYDcP8YYo&data=05%7C02%7Cgfay%40umassd.edu%7C97e2a7b9387046dc2c0a08dd566fb6a5%7C328d6c0d0f2f4b7693109762ba1c3e2d%7C0%7C0%7C638761760008112177%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=k2znX2FGecxjBia3GGAoNKVH1pzW6HejxPV1rKRpyyE%3D&reserved=0) (part 2), [here](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMGIMuxh-fx4&data=05%7C02%7Cgfay%40umassd.edu%7C97e2a7b9387046dc2c0a08dd566fb6a5%7C328d6c0d0f2f4b7693109762ba1c3e2d%7C0%7C0%7C638761760008125400%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=DfXYqkrPAGjHhZQxlQfM7Srz%2Fq9nbbK%2BPmjhc1IVBb0%3D&reserved=0) (part 3), [here](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DlJhn8W6N8rA&data=05%7C02%7Cgfay%40umassd.edu%7C97e2a7b9387046dc2c0a08dd566fb6a5%7C328d6c0d0f2f4b7693109762ba1c3e2d%7C0%7C0%7C638761760008137330%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=ooMwTBDcXBrevtrDz86SncSa8qX1nk1aLQ2GToY5B1o%3D&reserved=0) (part 4), and [here](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DjZT47_bfxgg&data=05%7C02%7Cgfay%40umassd.edu%7C97e2a7b9387046dc2c0a08dd566fb6a5%7C328d6c0d0f2f4b7693109762ba1c3e2d%7C0%7C0%7C638761760008149131%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=AZ5PzSFCNQRB2VRCx9q6M7KJyYDZCqWxmFORAioN7Qo%3D&reserved=0) (part 5).
